root = "."
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  # Binary file yields from `cmd`.
  bin = "./tmp/main"
  # Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  # Stop to run old binary when build errors occur.
  stop_on_error = true
  # Send Log output to stdout (useful for Docker logs)
  log = "air_errors.log"
  poll = true
  poll_interval = 500

[log]
  # Show log time
  time = false

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true